[package]
name = "kafka-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.8.0", features = ["serde"] }
byteorder = "1.5.0"
varint-rs = "2.2.0"
serde = { version = "1.0.203", features = ["derive"] }
log = "0.4.21"

[dev-dependencies]
serde_json = "1.0.117"
rstest = "0.21.0"
proptest = "1.4.0"
proptest-derive = "0.4.0"
base64 = "0.22.1"
